# Generated by Django 4.1 on 2022-08-29 11:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStart', models.DateTimeField()),
                ('timeEnd', models.DateTimeField()),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sports.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sports.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sports.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('bookingDate', models.DateField(default=datetime.datetime(2022, 8, 29, 11, 58, 29, 257979, tzinfo=datetime.timezone.utc))),
                ('bookingTime', models.DateTimeField(default=datetime.datetime(2022, 8, 29, 11, 58, 29, 257979, tzinfo=datetime.timezone.utc))),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sports.slot')),
            ],
        ),
    ]
