# Generated by Django 4.1 on 2022-09-03 09:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 3, 9, 45, 58, 216785, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 9, 45, 58, 216785, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sports.slot'),
        ),
    ]
