# Generated by Django 4.1 on 2022-08-31 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0002_alter_booking_bookingdate_alter_booking_bookingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 14, 52, 13, 536154, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 14, 52, 13, 536154, tzinfo=datetime.timezone.utc)),
        ),
    ]
