# Generated by Django 4.1 on 2022-09-02 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0003_slot_approved_alter_booking_bookingdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='approved',
            new_name='available',
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 2, 16, 42, 14, 922274, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 16, 42, 14, 922274, tzinfo=datetime.timezone.utc)),
        ),
    ]
